path(path,'/nfs/guille/tgd/users/irvine/matlabui')
path(path,'/nfs/guille/tgd/users/irvine/matlabui/questionnaire')
path(path,'/nfs/guille/tgd/users/irvine/matlabui/tutorial')
path(path,'/nfs/guille/tgd/users/irvine/matlabui/dataset') 
path(path,'/nfs/guille/tgd/users/irvine/matlabui/tests') 
path(path,'/nfs/guille/tgd/users/irvine/matlabui/algorithms') 
