% system
path(path,'C:\avatol\git\avatol_cv') 
path(path,'C:\avatol\git\avatol_cv\app') 
path(path,'C:\avatol\git\avatol_cv\questionnaire') 
path(path,'C:\avatol\git\avatol_cv\tests') 
path(path,'C:\avatol\git\avatol_cv\tutorial') 
path(path,'C:\avatol\git\avatol_cv\dataset') 
path(path,'C:\avatol\git\avatol_cv\algorithms')
% nematocyst
path(path,'C:\avatol\git\nematocyst\avatol_system')
path(path,'C:\avatol\git\nematocyst\avatol_system\parse_input')
path(path,'C:\avatol\git\nematocyst\avatol_system\postprocess')
path(path,'C:\avatol\git\nematocyst\avatol_system\preprocess')
path(path,'C:\avatol\git\nematocyst\avatol_system\utilities')
path(path,'C:\avatol\git\nematocyst')
% bat
path(path,'C:\avatol\git\bat')
path(path,'C:\avatol\git\bat\learning')
path(path,'C:\avatol\git\bat\detection')
path(path,'C:\avatol\git\bat\learning')
path(path,'C:\avatol\git\bat\rpm')
path(path,'C:\avatol\git\bat\siftflow')
path(path,'C:\avatol\git\bat\ssvm')
path(path,'C:\avatol\git\bat\util')
path(path,'C:\avatol\git\bat\visualization')
path(path,'C:\avatol\git\bat\chain_rpm')

%addpath( genpath('C:\avatol\git\bat') )
