path(path,'C:\avatol\git\avatol_cv') 
path(path,'C:\avatol\git\avatol_cv\questionnaire') 
path(path,'C:\avatol\git\avatol_cv\tests') 
path(path,'C:\avatol\git\avatol_cv\tutorial') 
path(path,'C:\avatol\git\avatol_cv\dataset') 
path(path,'C:\avatol\git\avatol_cv\algorithms') 
path(path,'C:\avatol\git\nematocyst')
path(path,'C:\avatol\git\bat')
