% system
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/questionnaire')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/tutorial')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/dataset') 
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/tests') 
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/algorithms') 
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/avatol_cv/app')
% nematocyst
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst/avatol_system')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst/avatol_system/parse_input')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst/avatol_system/postprocess')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst/avatol_system/preprocess')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/nematocyst/avatol_system/utilities')
% bat
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat/rpm')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat/siftflow')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat/ssvm')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat/util')
path(path,'/nfs/guille/bugid/bugid/AVATOL/av_cv/git/bat/visualization')
