classdef ResultsReviewScreen < handle
    %RESULTSREVIEW Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        ui;
        session;
        metadataKeyIndex = 0;
        metadataKeyCount = 0;
        keys;
        ssm;
        input_folder;
        output_folder;
        detection_results_folder;
    end
    
    methods
        function obj = ResultsReviewScreen(ui, session)
            obj.ui = ui;
            obj.session = session;
        end
        function reset(obj)
            obj.ssm = obj.session.scoredSetMetadata;
            obj.ssm.loadAll();
            obj.keys = obj.ssm.getKeys();
            obj.metadataKeyCount = obj.keys.size();
            obj.metadataKeyIndex = obj.metadataKeyCount - 1;
            obj.updateFolders();
        end
        function showResults(obj)
            curKey = obj.keys.get(obj.metadataKeyIndex);
            curMetadata = obj.ssm.getDisplayableDataForKey(curKey);
            obj.ui.deleteObsoleteControls();
            obj.ui.createResultsReviewPanels();
            % create panel for instructions
		
            scoredSetPrompt = uicontrol('style', 'text' ,...
                                         'Parent',obj.ui.scoredSetTitlePanel,...
                                         'Units','normalized',...
                                         'String', 'Select scored set to review.' ,...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','scoredSetPrompt' ,...
                                         'Background',[1 1 1],...
                                         'HorizontalAlignment', 'left');%'BackgroundColor', [0.1 1 0.1] ,...
            metadataContent = uicontrol('style', 'text' ,...
                                         'Parent',obj.ui.scoredSetMetadataPanel,...
                                         'Units','normalized',...
                                         'String', char(curMetadata) ,...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','metadataContent' ,...
                                         'Background',[1 1 1],...
                                         'HorizontalAlignment', 'left');%'BackgroundColor', [0.1 1 0.1] ,...
            
            nextButtonNeeded = false;
            backButtonNeeded = false;
            if obj.metadataKeyCount==1
                % no navigationButtons
            else
                if obj.metadataKeyIndex > 0
                    backButtonNeeded = true;
                end
                if obj.metadataKeyIndex < obj.metadataKeyCount - 1
                    nextButtonNeeded = true;
                end
            end
            
            % create panel for training images
		
            % create panel for scored images
		
            
             doAnotherCharacter = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Try another character' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units', 'normalized',...
                                         'position', obj.ui.getButtonPositionLeft() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','doAnotherCharacter' ,...
                                         'BackgroundColor', [0.5 0.5 0.5]);  

            
             exit = uicontrol('style', 'pushbutton' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'String', 'Exit' ,...
                                         'position', obj.ui.getButtonPositionRightB() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','exit' ,...
                                         'BackgroundColor', [0.5 0.5 0.5]);  
            obj.ui.activeControlTags = { 'scoredSetPrompt', 'doAnotherCharacter', 'metadataContent', 'exit' };
            if backButtonNeeded
                prev = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Previous Run' ,...
                                         'Units','normalized',...
                                         'position', [0,0,0.4,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Parent',obj.ui.scoredSetNavigationPanel,...
                                         'Tag','prev' ,...
                                         'BackgroundColor', [0.5 0.5 0.5]); 
                 set(prev, 'callback', {@obj.showPreviousMetadata});
                 obj.ui.activeControlTags = [  obj.ui.activeControlTags , 'prev' ];
            end
            if nextButtonNeeded
                next = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Next Run' ,...
                                         'Units','normalized',...
                                         'position', [0.6,0,0.4,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','next' ,...
                                         'parent',obj.ui.scoredSetNavigationPanel,...
                                         'BackgroundColor', [0.5 0.5 0.5]);   
                
                set(next, 'callback', {@obj.showNextMetadata});
                obj.ui.activeControlTags = [  obj.ui.activeControlTags , 'next' ];
            end
            % ???????? obj.ui.activeAnswerControl = obj.taxonChoiceWidget;
            obj.session.activeQuestionId = 'ResultsReview';
            obj.ui.activeControlType = 'ResultsReview';

            set(exit, 'callback', {@obj.exit});
            set(doAnotherCharacter, 'callback', {@obj.doAnotherCharacter});
            obj.session.mostRecentScreen = 'RESULTS_REVIEW_SCREEN'; 
            fprintf('would now load from output folder %s', char(obj.output_folder));
        end
        function updateFolders(obj)
            curKey = obj.keys.get(obj.metadataKeyIndex);
            obj.input_folder = obj.ssm.getInputFolderForKey(curKey);
            obj.output_folder = obj.ssm.getOutputFolderForKey(curKey);
            obj.detection_results_folder = obj.ssm.getDetectionResultsFolderForKey(curKey);
        end
        function showNextMetadata(obj, hObject, eventData)
            obj.metadataKeyIndex = obj.metadataKeyIndex + 1;
            obj.updateFolders();
            obj.showResults();
        end
        function showPreviousMetadata(obj, hObject, eventData)
            obj.metadataKeyIndex = obj.metadataKeyIndex - 1;
            obj.updateFolders();
            obj.showResults();
        end
        function doAnotherCharacter(obj,hObject, eventData)
            obj.session.doAnotherCharacter();
        end
        function exit(obj, hobject, eventData)
            obj.session.exit();
        end
    end
    
end

