classdef ResultsReviewScreen < handle
    %RESULTSREVIEW Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        ui;
        session;
    end
    
    methods
        function obj = ResultsReviewScreen(ui, session)
            obj.ui = ui;
            obj.session = session;
        end
        function showResults(obj)
            obj.ui.deleteObsoleteControls();
            obj.ui.createResultsReviewPanels();
            % create panel for instructions
		
             scoredSetPrompt = uicontrol('style', 'text' ,...
                                         'Parent',obj.ui.scoredSetTitlePanel,...
                                         'Units','normalized',...
                                         'String', 'Select scored set to review.' ,...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','scoredSetPrompt' ,...
                                         'Background',[1 1 1],...
                                         'HorizontalAlignment', 'left');%'BackgroundColor', [0.1 1 0.1] ,...
            % create panel for training images
		
            % create panel for scored images
		
            % create panel for feedback
            
            
             doAnotherCharacter = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Try another character' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units', 'normalized',...
                                         'position', obj.ui.getButtonPositionLeft() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','doAnotherCharacter' ,...
                                         'BackgroundColor', [0.5 0.5 0.5]);  

            
             exit = uicontrol('style', 'pushbutton' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'String', 'Exit' ,...
                                         'position', obj.ui.getButtonPositionRightB() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','exit' ,...
                                         'BackgroundColor', [0.5 0.5 0.5]);  
            obj.ui.activeControlTags = { 'scoredSetPrompt', 'doAnotherCharacter', 'exit' };
            % ???????? obj.ui.activeAnswerControl = obj.taxonChoiceWidget;
            obj.session.activeQuestionId = 'ResultsReview';
            obj.ui.activeControlType = 'ResultsReview';

            set(exit, 'callback', {@obj.exit});
            set(doAnotherCharacter, 'callback', {@obj.doAnotherCharacter});
            obj.session.mostRecentScreen = 'DPM_TAXON_QUESTION'; 
        end
        function doAnotherCharacter(obj,hObject, eventData)
            obj.session.doAnotherCharacter();
        end
        function exit(obj, hobject, eventData)
            obj.session.exit();
        end
    end
    
end

