classdef TutorialScreens < handle
    %TUTORIAL Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        tutorialXML;
        infoPageSequencer;
        mostRecentTutorialPage = 'NOT_STARTED';
        ui;
        session;
    end
    
    methods
        function obj = TutorialScreens(ui, session)
            obj.ui = ui;
            obj.session = session;
            if ispc
                obj.tutorialXML = 'data\\tutorial\\Tutorial.xml';
            else
                obj.tutorialXML = 'data/tutorial/Tutorial.xml';
            end
    
            tutorialXmlFile = QuestionsXMLFile(obj.tutorialXML);
            infoPages = InfoPages(tutorialXmlFile.domNode);
            obj.infoPageSequencer = InfoPageSequencer(infoPages);
            ipv = InfoPagesValidator();
            ipv.validate(obj.infoPageSequencer.info_pages.info_pages);
        end
        

        function displayTutorialPage(obj,infoPage)
            obj.ui.deleteObsoleteControls();
            obj.ui.createTutorialPanels();

            titleString = sprintf('Tutorial');
            characterNameText = obj.ui.getCharacterNameTitle(titleString);

            tutorialText = uicontrol('style', 'text' ,...
                                         'String', infoPage.text ,...
                                         'Units','normalized',...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'BackgroundColor', [1 1 1] ,...
                                         'Tag','tutorialText' ,...
                                         'Parent',obj.ui.textPanel,...
                                         'HorizontalAlignment', 'left');
            skipToQuestionnaireButtonPosition = [0,0,0.25,1 ];
            skipToResultsReviewButtonPosition = [0.26,0,0.23,1 ];
            skipToQuestionnaire = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Skip to Questionnaire' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToQuestionnaireButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','skipToQuestionnaire' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  
            skipToResultsReview = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Review Results' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToResultsReviewButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','skipToResultsReview' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  


             next = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Next' ,...
                                         'Units','normalized',...
                                         'position', obj.ui.getButtonPositionRightB() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','next' ,...
                                         'parent',obj.ui.navigationPanel,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

             prev = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Back' ,...
                                         'Units','normalized',...
                                         'position', obj.ui.getButtonPositionRightA() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Tag','prev' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

            obj.ui.activeControlTags = { 'tutorialText', 'skipToResultsReview', 'next', 'prev', 'skipToQuestionnaire'}; 
            
             if (obj.session.scoredSetMetadatas.hasSessionData())
                set(skipToResultsReview, 'Enable', 'on');
            else
                set(skipToResultsReview, 'Enable', 'inactive');
                set(skipToResultsReview, 'BackgroundColor', [0.8 0.8 0.8]);
                set(skipToResultsReview, 'ForegroundColor', [0.6 0.6 0.6]);
             end
            
            obj.session.activeScreen = 'TutorialPage';
            set(next, 'callback', {@obj.showNextTutorialPage});
            set(prev, 'callback', {@obj.showPrevTutorialPage});
            set(skipToResultsReview, 'callback', {@obj.jumpToResultsReview});
            set(skipToQuestionnaire, 'callback', {@obj.jumpToQuestionnaire});
            if (not(isempty(infoPage.images)))
                obj.ui.displayImages(infoPage.images);
            end
            obj.mostRecentTutorialPage = infoPage.id;
        end

        function displayTutorialGoalPage(obj)
            obj.ui.deleteObsoleteControls();
            obj.ui.createSimpleTextScreenPanels();
            lineA = 'The goals of this tutorial are to:';
            lineA1 = '';
            lineA2 = '';
            lineB = '    1) Map biological terminology into computer vision terminology';
            lineC = '';
            lineD = '        - What is a biological character in computer vision terms?';
            lineE = '';
            lineF = '        - What is a character score in computer vision terms?';
            lineG = '';
            lineH = '';
            lineI = '    2) Explain general concepts about images and computer vision';
            goalText = { lineA lineA1 lineA2 lineB lineC lineD lineE lineF lineG lineH lineI };

            tutorialText = uicontrol('style', 'text' ,...
                                         'String', goalText ,...
                                         'Units','normalized',...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'BackgroundColor', [1 1 1] ,...
                                         'Tag','tutorialText' ,...
                                         'Parent',obj.ui.textPanel,...
                                         'HorizontalAlignment', 'left');

            skipToQuestionnaireButtonPosition = [0,0,0.25,1 ];
            skipToResultsReviewButtonPosition = [0.26,0,0.23,1 ];
            skipToQuestionnaire = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Score a Character' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToQuestionnaireButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','skipToQuestionnaire' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  
            skipToResultsReview = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Review Results' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToResultsReviewButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','skipToResultsReview' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

             next = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Next' ,...
                                         'Units','normalized',...
                                         'position', obj.ui.getButtonPositionRightB() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','next' ,...
                                         'parent',obj.ui.navigationPanel,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

             prev = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Back' ,...
                                         'Units','normalized',...
                                         'position', obj.ui.getButtonPositionRightA() ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Tag','prev' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

            obj.ui.activeControlTags = { 'tutorialText', 'skipToResultsReview', 'next', 'prev', 'skipToQuestionnaire'};  
            if (obj.session.scoredSetMetadatas.hasSessionData())
                set(skipToResultsReview, 'Enable', 'on');
            else
                set(skipToResultsReview, 'Enable', 'inactive');
                set(skipToResultsReview, 'BackgroundColor', [0.8 0.8 0.8]);
                set(skipToResultsReview, 'ForegroundColor', [0.6 0.6 0.6]);
            end
            
            obj.session.activeScreen = 'TUTORIAL_GOAL';
            set(next, 'callback', {@obj.showCurrentTutorialPage});
            set(prev, 'callback', {@obj.backUpFromTutorial});
            set(skipToQuestionnaire, 'callback', {@obj.jumpToQuestionnaire});
            set(skipToResultsReview, 'callback', {@obj.jumpToResultsReview});
            obj.mostRecentTutorialPage = 'TUTORIAL_GOAL';
        end
        
        function jumpToResultsReview(obj,hObject, eventData)
            obj.session.jumpToResultsReview();
        end
        function jumpToQuestionnaire(obj, hObject, eventData)
            obj.session.jumpToQuestionnaire();
        end
        function backUpFromTutorial(obj, hObject, eventData)
            obj.session.backUpFromTutorial();
        end
        function startTutorial(obj)
            obj.displayTutorialGoalPage();
        end
        function showNextTutorialPage(obj, hObject, eventData)
            % we've already started the tutorial, check to see if we can
            % move forward
            infoPage = obj.infoPageSequencer.getCurrentInfoPage();
            if (strcmp(infoPage.next,'NO_MORE_PAGES'))
                obj.displayFinishedTutorialScreen();
            else
                obj.infoPageSequencer.moveToNextPage();
                infoPage = obj.infoPageSequencer.getCurrentInfoPage();
                obj.displayTutorialPage(infoPage);
            end
        end

        function showPrevTutorialPage(obj, hObject, eventData)
            if (strcmp(obj.session.activeScreen,'SummaryScreen'))
                % we're backing up from the TutorialDone screen - just
                % show the currently referenced page
                infoPage = obj.infoPageSequencer.getCurrentInfoPage();
                obj.displayTutorialPage(infoPage);
            elseif (obj.infoPageSequencer.canBackUp())
                obj.infoPageSequencer.backUp();
                infoPage = obj.infoPageSequencer.getCurrentInfoPage();
                obj.displayTutorialPage(infoPage);
            else
                obj.displayTutorialGoalPage();
            end
        end


        function displayFinishedTutorialScreen(obj) 
            obj.ui.deleteObsoleteControls();
            obj.ui.createSimpleTextScreenPanels();
            summaryTextString = ['You have completed the tutorial.  '...
                         'You may score a character, review prior results, or exit.'];

            summaryText = uicontrol('style', 'text' ,...
                                         'String', summaryTextString ,...
                                         'Units','normalized',...
                                         'position', [0,0,1,1] ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'BackgroundColor', [1 1 1] ,...
                                         'Tag','summaryText' ,...
                                         'Parent',obj.ui.textPanel,...
                                         'HorizontalAlignment', 'left');

            skipToQuestionnaireButtonPosition = [0,0,0.25,1 ];  
            skipToResultsReviewButtonPosition = [0.26,0,0.23,1 ];
            prevButtonPosition =                [0.6,0,0.15,1];                       
            beginQuestionnaireButtonPosition =  [0.75,0,0.25,1 ];
            beginQuestions = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Score a Character' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', beginQuestionnaireButtonPosition,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','beginQuestionnaire' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);   
            skipToResultsReview = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Review Results' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToResultsReviewButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','skipToResultsReview' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

             prev = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Prev' ,...
                                         'Units','normalized',...
                                         'position', prevButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Tag','prev' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);                   
            exitButton = uicontrol('style', 'pushbutton' ,...
                                         'String', 'Exit' ,...
                                         'Parent',obj.ui.navigationPanel,...
                                         'Units','normalized',...
                                         'position', skipToQuestionnaireButtonPosition ,...
                                         'FontName', obj.ui.fontname ,...
                                         'FontSize', obj.ui.fontsize ,...
                                         'Tag','exit' ,...
                                         'BackgroundColor', [0.8 0.8 0.8]);  

            obj.ui.activeControlTags = { 'summaryText','skipToResultsReview',  'beginQuestionnaire', 'exit', 'prev' };   

             if (obj.session.scoredSetMetadatas.hasSessionData())
                set(skipToResultsReview, 'Enable', 'on');
            else
                set(skipToResultsReview, 'Enable', 'inactive');
                set(skipToResultsReview, 'BackgroundColor', [0.8 0.8 0.8]);
                set(skipToResultsReview, 'ForegroundColor', [0.6 0.6 0.6]);
             end
            
            obj.session.activeScreen = 'SummaryScreen';
            set(beginQuestions, 'callback', {@obj.startQuestions});
            set(skipToResultsReview, 'callback', {@obj.jumpToResultsReview});
            set(exitButton, 'callback', {@obj.exit});
            set(prev, 'callback', {@obj.showPrevTutorialPage});
            obj.mostRecentTutorialPage = 'TUTORIAL_COMPLETE';
        end
        function exit(obj, hObject, eventData)
            obj.session.exit();
        end
        function startQuestions(obj, hObject, eventData)
            obj.session.startQuestions();
        end
        function showCurrentTutorialPage(obj, hObject, eventData)
            infoPage = obj.infoPageSequencer.getCurrentInfoPage();
            obj.displayTutorialPage(infoPage);
        end
        
        
    end
    
end

